language: ruby
rvm:
  - "1.9.3" 
env: TEST_DATABASE_URL=postgres://postgres@locahost/travispopup DATABASE_URL=postgres://postgres@localhost/travispopup RAILS_ENV=test
script: bundle exec rake
before_script:
  - rake db:create db:schema:load
bundler_args: --without development
services:
  - elasticsearch
